### ISSUE TITLE
Error in Travis: Could not start Sauce Connect. Exit code 1 signal: null

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/sqlite-plugin-2#2]
Oddly, I can run this test against Sauce Labs on my home machine (Mac OS X), but not on Travis (also OS X). The error is not very enlightening:

```
Error: Could not start Sauce Connect. Exit code 1 signal: null
    at ChildProcess.<anonymous> (/Users/travis/build/nolanlawson/sqlite-plugin-2/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:308:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

An example of a failed job is [here](https://travis-ci.org/nolanlawson/sqlite-plugin-2/jobs/120324452). Not sure what I should be doing.

**Comment by nolanlawson** [comment]
Here's the [.travis.yml](https://github.com/nolanlawson/sqlite-plugin-2/blob/f9d6ccf64541d465f11883cda77001cec3b3b391/.travis.yml) for that failed job.

**Comment by nolanlawson** [comment]
I filed [a support request on Sauce](https://support.saucelabs.com/customer/en/portal/questions/16239587-could-not-start-sauce-connect-exit-code-1-signal-null?new=16239587).

**Comment by nolanlawson** [comment]
Weird, it appears that Travis isn't running the npm postinstall task for `sauce-connect-launcher`. So the fix is to manually add:

```bash
SAUCE_CONNECT_DOWNLOAD_ON_INSTALL=true node node_modules/sauce-connect-launcher/scripts/install.js
```

**Comment by nolanlawson** [comment]
it was a bad zip file
